### PR TITLE
Update header levels/spacing

### LINKED ISSUE #105: Some header levels are inconsistent, spacing off
Some headers jump sequence, others have inconsistent spacing around them which (I vaguely recall) interferes with some rendering.

Going to reference this issue for an upcoming PR, potential further discussion.

### PR DESCRIPTION
**Pull request by atc0005**
## Purpose

Update header levels and immediate spacing around them.

## Why

As I read through the book I noticed that formatting was off in places, often when code ran up against headers or other blocks of content. I also noticed that some header levels appeared "off".

This PR is focused specifically on the header levels with follow-up PRs for other indirectly related formatting issues.

fixes #105

### CODE REVIEW

**Comment by atc0005** [comment]
As noted on #105, I opened this PR (in its draft form) for review purposes. I plan to squash the commits and add a useful log message once the changes look good.

**Comment by atc0005** [comment]
Note: not rushing in any way, just wanted to explicitly note that I'm waiting for feedback before moving further with this or related work. I looked back over my earlier notes and realized that I wasn't really clear about that.

**Comment by thewhitetulip** [comment]
Hey, sorry. Have been very busy. Give me some time.

**Comment by atc0005** [comment]
> Hey, sorry. Have been very busy. Pleass give me some time.

Not a problem, I completely understand.

**Comment by thewhitetulip** [comment]
Hey man, do you want to be a collaborator on this project? I'll be happy to make you one. That way, you can commit to the repo without my "approval"

**Comment by atc0005** [comment]
> Hey man, do you want to be a collaborator on this project? I'll be happy to make you one. That way, you can commit to the repo without my "approval"

Certainly, I'm honored that you have made this offer. What do you propose to be the scope of my involvement? I primarily want to make sure that I don't exceed them and cause you any difficulties.

**Comment by thewhitetulip** [comment]
You can do anything. Review the PR if you have time, change things etc. I don't have any issues.

**Comment by thewhitetulip** [comment]
I've sent you an invite. Not sure how you'll access it though. and good luck!!

**Comment by thewhitetulip** [comment]
I'm logging off, have a good day.

**Comment by atc0005** [comment]
> I've sent you an invite. Not sure how you'll access it though. and good luck!!

Accepted, thanks!

> You can do anything. Review the PR if you have time, change things etc. I don't have any issues.

Acknowledged, I'll do my best to keep the changes focused in an effort to make them easier to review later (if needed). Do you wish to be mentioned for PRs that I submit/merge?

Are you open to the idea of creating a development (or testing or some other similarly named) branch and then setting up Leanpub to accept GitHub push requests in order to generate Preview builds for the new branch?

I gave it a try on my free account and it worked well for proofing changes.

**Comment by thewhitetulip** [comment]
You can take a call about everything. If you have time then feel free and review PRs sent by others. I have moved away from Go so won't be aware of the new developments in the language.

Tdlr; you are a part of the team now! You can take your well thought out and positive  decisions without asking me. I'm reachable via email if you really need me. But I don't think you will need me though.

**Comment by atc0005** [comment]
@thewhitetulip 

Acknowledged and thanks for clarifying. Thanks also for the open invitation to reach out by direct email when I need to. I'll try to keep those to a minimum, but I appreciate the open door.

I have limited time and limited skill with Go (very much a newbie at this point), but I will do what I can to help.

Are you open to periodically regenerating new copies of the book via leanpub (and anywhere else you're publishing it)? If so, would you find it helpful to be pinged by direct email, by opening a new issue and assigning it directly to you? 

To make things easier for us both, I'll probably keep regenerating new draft copies via my free leanpub account; only after a large batch is ready will I request a new official copy of the book be regenerated (again, assuming you're open to receiving periodic requests to refresh the book).

**Comment by thewhitetulip** [comment]
You can send me an email anytime. I don't mind. I'll update leanpub copy every week, that makes sense right?

**Comment by atc0005** [comment]
Thanks for agreeing to receive emails.

Re leanpub, maybe not weekly, but monthly or by request?

 I can open an issue and assign to you or send an email when enough changes are ready for publishing.

**Comment by thewhitetulip** [comment]
Sure. I don't mind that.

**Comment by atc0005** [comment]
Generating a test copy based on this rebased branch. Will check for obvious issues before merging in the next day or so.

**Comment by atc0005** [comment]
The only bits I'm not 100% sure about are the intended Table of Contents entries: what is intended to be top-level headings and which sub-heading.

I've attached a draft PDF copy for quick review (just the ToC entries).

If you don't have the time I can go with my initial impression and make whatever fixes are needed later.

[antitextbookgo-atc0005-unofficialfork-preview.pdf](https://github.com/thewhitetulip/web-dev-golang-anti-textbook/files/3495386/antitextbookgo-atc0005-unofficialfork-preview.pdf)

There are still other changes to make regarding formatting, but I'd like to include those in separate PRs to keep the changes distinct and (hopefully) easier to follow.

**Comment by thewhitetulip** [comment]
Hey, pls go ahead and make changes. I'll fix issues later :)

**Comment by atc0005** [comment]
> Hey, pls go ahead and make changes. I'll fix issues later :)

Fair enough. It was mainly the intended section order that I was considering a blocker of sorts, but if you see that I've set the headers wrong I guess open an issue? :)

I'll review this in a bit and get it merged.

**Comment by atc0005** [comment]
@thewhitetulip Merged. More to come soon.

**Pull request merged**
